version: '2.1'
services:
  webtop:
    image: lscr.io/linuxserver/webtop
    network_mode: host
    privileged: true
    volumes:
      - webtop:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - KEYBOARD=en-us-qwerty
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      - io.balena.features.dbus: '1'
      - io.balena.features.firmware: '1'
    environment:
      - CHECK_CONN_FREQ=6000
      - PORTAL_SSID=webtop
volumes:
  webtop: